/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_softsum_jxd_learn_jniTest_JniTest */

#ifndef _Included_com_softsum_jxd_learn_jniTest_JniTest
#define _Included_com_softsum_jxd_learn_jniTest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_softsum_jxd_learn_jniTest_JniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_softsum_jxd_learn_jniTest_JniTest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
